PATCH http://localhost:3000/61b14df70079675612a09e36 
Content-Type: application/json

{
  "brand": "update2",
  "model": "update2",
  "price": 123456,
  "amount": 100,
  "specs": {
    "cpu": "5ghz",
    "ram":8,
    "storage": 256
  }
}